.github/actions/helm-docs/README.md, .github/workflows/build-and-push-docker-image.yaml, .github/workflows/generate-tf-helm-docs.yaml, README.md, infra-tools/Makefile
- update the code to use new tag naming conventions
- https://ticketsystem.hpi-schul-cloud.org/browse/OPS-2954
- functionality itself shouldn't be affected
n/a
n/a
n/a
n/a
=> adjusting to new tags naming conventions

.gitignore, sct/README.md, sct/requirements.txt, sct/sct.py
Add gitssh tunneling to sct
- https://ticketsystem.schul-cloud.org/browse/OPS-2996
Add gittssh tunneling
N/A
N/A
N/A
N/A
=> Ops 2996 gitea tunneling

sct/README.md, sct/sct.py
=> Canged some typos and added keyboard interrupt handler

.github/workflows/dbcmtoghcr-on-push.yaml, dbcmetrics/dbcm_logic/dbcversion.py
New workflow which will push Docker images to GHCR for branches except master, skip-ci
=> Ops 3080 build and push docker images ghcr

s3-backup/s3b_prod.yaml
=> [OPS-3120] delete open demo bayern instance from s3 backup

dbcmetrics/dbcm_config_template.yaml, dbcmetrics/dbcm_logic/dbcversion.py
=> OPS-3224 Removed instance name from metric names

s3-backup/s3b_prod.yaml
=> [OPS-3120] last cleanup

dbcmetrics/dbcm_logic/dbcversion.py
=> OPS-3338 Added clear to do_something to remove old metrics

onepwd/plugins/action/update_s3_values_of_item.py, onepwd/plugins/action/update_s3_values_of_server_item.py, onepwd/plugins/action/upload_s3_secret.py, onepwd/src/onepwd/__init__.py
add naming functionality for uploading s3 secrets
https://ticketsystem.dbildungscloud.de/browse/OPS-3313
n/a
n/a
n/a
n/a
n/a
=> OPS-3313-add-naming-functionality-to-ansible-action-upload-s3-secret

.github/actions/helm-docs/README.md
fix grammar in helm-docs Github Action
=> correct spelling of helm-docs action

dbcmetrics/dbcm_logic/dbcstorage.py
If the fetching time is longer than the configured interval time, then the dbcmetrics storage monitoring module was sleeping where it should already be fetching data to get as close to the configured interval as possible.
OPS-3400
[infra-schulcloud  #213 - OPS-3400: dbcmetrics prod hpibosscloud OOM Killed](https://github.com/hpi-schul-cloud/infra-schulcloud/pull/213)
Fix that the storage monitoring module will wait the interval time additionally after fetching so that in will only wait if the fetching time is below the waiting time.
Deployed to infra-dev-schulcloud-1, sc-dev-devcenter-1, sc-staging-legacy, sc-prod-legacy.
=> OPS-3400: dbcmetrics prod hpibosscloud OOM Killed

onepwd/plugins/action/update_s3_values_of_item.py, onepwd/setup.py, onepwd/src/onepwd/__init__.py
=> [OPS-3361] add IONOS S3 Backup to onepwd

ansible_collections/galaxy.yml, dbcmetrics/README.md, onepwd/galaxy.yml
rename schulcloud to dbildungscloud
https://ticketsystem.dbildungscloud.de/browse/OPS-3290
=> OPS-3290 rename namespace in ansible collections

onepwd/galaxy.yml, onepwd/plugins/action/create_s3_item.py, onepwd/plugins/action/update_s3_values_of_item.py, onepwd/plugins/action/upload_s3_secret.py, onepwd/src/onepwd/__init__.py
write a new plugin to be able to generate a dummy secret, in which the update_s3_item action can edit the s3_credentials-. Helps to automate the process of user and buckets creation. 
https://ticketsystem.dbildungscloud.de/secure/RapidBoard.jspa?rapidView=77&projectKey=OPS&view=detail&selectedIssue=OPS-3484&quickFilter=1071
=> Ops 3484 nextcloud s3 backup refactoring

infra-tools/Dockerfile
make infra-tools containers base image an ubuntu image for better security
also make infra-tools container use the newest duplicity version, so boto3 can be used
https://ticketsystem.dbildungscloud.de/browse/OPS-3545
=> Ops 3545 fix infra tools vulnerabilities

dbcmetrics/dbcm_config_template.yaml, infra-tools/Dockerfile
=> OPS-3561 dbcm changes

dbcmetrics/dbcm_logic/dbcstorage.py
=> OPS-3323 Fixed behavior when bucket is empty

sct/requirements.txt, sct/sct.py, sct/sct_common/sct_tools.py, sct/sct_logic/tunnel.py, sct/sct_logic/update.py
- Update the tool to use the ionoscloud API 6.x
- Extended to run properly on WSL2
-- gsudo.exe and hostctl.exe must be in path
=> Use new ionoscloud API 6.0.x, handles WSL correct

onepwd/galaxy.yml, onepwd/plugins/action/create_s3_item.py, onepwd/plugins/action/update_s3_values_of_item.py, onepwd/plugins/action/upload_s3_secret.py, onepwd/setup.py, onepwd/src/onepwd/__init__.py, sct/requirements.txt
Updated the onepwd module for CLI 2
Ticket: https://ticketsystem.dbildungscloud.de/browse/OPS-3345
=> Ops 3345 update onepwd cli 2

sct/sct_common/sct_tools.py
SCT supports now caching for sudo under WSL
=> Cache duration remains unless sct session is terminated

onepwd/galaxy.yml, onepwd/src/onepwd/__init__.py
https://ticketsystem.dbildungscloud.de/browse/OPS-3813
=> OPS-3813-1Password-Update-s3-values-not-working-with-nextcloud-item

.gitignore, prod-container-list/README.md, prod-container-list/prod_container_list.sh
=> [OPS-3804] add shellscript

dbcmetrics/Dockerfile, dbcmetrics/dbcm_logic/dbcstorage.py
Add logging of exception info to dbcmetric. 
Updated base image to `python:3.10-alpine`.
https://ticketsystem.dbildungscloud.de/browse/OPS-4303
=> OPS-4303-Logging-exception-information-in-dbcmetrics

.github/workflows/imagetoghcr-on-push.yaml
=> OPS-4370 Added permission for private repos to image to GHCR on push

dbcmetrics/dbcm.py, dbcmetrics/dbcm_common/dbcm_config.py, dbcmetrics/dbcm_common/repeating_thread.py, dbcmetrics/dbcm_config_template.yaml, dbcmetrics/dbcm_logic/dbcionosmaintenance.py, dbcmetrics/dbcm_logic/dbcplannedmaintenance.py, dbcmetrics/dbcm_logic/dbcstorage.py, dbcmetrics/dbcm_logic/dbcversion.py
Storage module rewritten to split availability and stats monitoring and reduce memory usage.
Some smaller changes/refactoring.
[OPS-4334](https://ticketsystem.dbildungscloud.de/browse/OPS-4334)
[OPS-3377](https://ticketsystem.dbildungscloud.de/browse/OPS-3377)
- Extracted the creation of a thread that repeats a task in a given interval (used in every module) into a separate class
- Availability and Stats (file count and size) are monitored in two different threads to get availability metrics more frequently
- Moved configs (except secrets) into the config file to match the structure used by the other modules
- Bucket stats are aggregated in the loop instead of saving all information to decrease the memory required
- Added option for retries if an exception occurs while fetching bucket …
=> OPS-4334-split-dbcmetrics-storage-metrics-decrease-mem-usage

onepwd/plugins/action/item.py, onepwd/plugins/modules/item.py, onepwd/setup.py, onepwd/src/onepwd/__init__.py
Adds two options to the onepwd plugin:
- Let 1password generate a password according to the specified rules (characters, length)
- Overwrite option (default: true) to allow keeping already generated password by setting it to false
Small fix: Skip fields without label instead of crashing.
[OPS-4474](https://ticketsystem.dbildungscloud.de/browse/OPS-4474)
=> OPS-4474-evaluate-kubernetesproxy-Add options to generate passwords and not overwriting existing ones

.github/workflows/build-and-push.yaml
=> Ops 4421 automate edusharing

infra-tools/Dockerfile
=> Updated infra-tools container to ubuntu 22.04

Makefile, sct/sct.py, sct/sct_common/run_command.py, sct/sct_common/sct_tools.py, sct/sct_data/shellcmd.py, sct/sct_logic/tunnel.py
SCT has been adapted to devcontainer
https://ticketsystem.dbildungscloud.de/browse/OPS-4798
=> Ops 4798 adapt sct to devcontainer

kubeconfig-automation/decrypt-kubeconfigs.sh
Added the decrypt-kubeconfigs.sh script (previously located in the infra-schulcloud repository).
Moved 
=> OPS-4994-move-decryption-script

awx-ee/_build/requirements.txt
Add PyYaml and passlib to AWX EE requirements.
=> OPS-5104-update-AWX-EE-requirements

dbcmetrics/requirements.txt
Update PyYaml requirement to version 6.0.1 used in infra-schulcloud and the AWX EE.
[OPS-5104](https://ticketsystem.dbildungscloud.de/browse/OPS-5104)
=> OPS-5104-update-pyyaml-requirement-dbcmetrics

.github/workflows/trigger-awx.yaml
=> Ops 5155 evaluate triggering awx from GitHub

.github/workflows/trigger-awx.yaml
=> Ops 5162 make personal infra devs work on awx

.github/workflows/ansible-count-hosts.yaml, .github/workflows/filter-branch-name.yaml
=> Ops 5460 fix personal infra dev rebuild

onepwd/README.md, onepwd/galaxy.yml, onepwd/playbook-test-onepwd.yml, onepwd/plugins/action/item.py, onepwd/plugins/modules/item.py
- add functionality for overwrite var of single field
- if a entry/label with that name already exists it is skipped
=> DBP-680-add-functionalit-to-onepwd

.github/workflows/bapontag.yaml, .github/workflows/build-and-push.yaml
=> Ops-5187 infra tools push to quay

.github/workflows/bapontag.yaml, .github/workflows/build-and-push.yaml
=> Ops-5187 enable push to quay

.github/workflows/bapontag.yaml
=> Ops-6222-multi-registry-push

.github/workflows/bapontag.yaml
=> OPS-6248-upgrade-image-publish-gha

onepwd/src/onepwd/__init__.py
- Rename exceptions to common python exception naming
- Throw Exception instead of passing a message to sys.exit, this properly prints during failure
Note:
I did not extend the testing of this, since it is hard to include tests for a failing module. If there is a trick to it please feel free to tell me.
[OPS-3335](https://ticketsystem.dbildungscloud.de/browse/OPS-3335)
=> Ops 3335 fix error messages when op_ credentials are faulty

onepwd/galaxy.yml, onepwd/src/onepwd/__init__.py
Increase module version
https://ticketsystem.dbildungscloud.de/browse/OPS-3335
=> Ops-3335 fix error messages

.gitignore, onepwd/credentials.json.j2, onepwd/galaxy.yml, onepwd/playbook-test-onepwd.yml, onepwd/plugins/action/create_s3_item.py, onepwd/plugins/action/document.py, onepwd/plugins/action/item.py, onepwd/plugins/action/share.py, onepwd/plugins/action/update_s3_values_of_item.py, onepwd/plugins/action/upload_s3_secret.py, onepwd/plugins/lookup/onepwd.py, onepwd/plugins/modules/document.py, onepwd/plugins/modules/item.py, onepwd/plugins/modules/share.py, onepwd/src/onepwd/__init__.py
- Add possibility to login with credentials as parameter, as well as login with credentials as file. 
- Extend Tests to test action and the lookup module once each
- add temporarily generated credentials.json to .gitignore in case deletion fails to prevent accidental commits
- extend documentation for logins 
https://ticketsystem.dbildungscloud.de/browse/OPS-6395
=> Ops 6395 allow credentials to be configured flexibly

infra-tools/Dockerfile
Update the docker image for infra-tools to the mongo version 6.
- https://ticketsystem.dbildungscloud.de/browse/BC-7461
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/889
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5082
- https://github.com/hpi-schul-cloud/docker-compose/pull/73
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/455
=> BC-7461 - Update mongo to v6

awx-ee/_build/requirements.txt
Update Ionoscloud requirements (see https://github.com/hpi-schul-cloud/infra-schulcloud/pull/1177)
`ansible-builder build -c . --tag='awx-ee'` ran successfully and resulted in no further changes.
=> OPS-6674-update-add-requirements

onepwd/plugins/action/item.py
=> OPS-6558 Fix bug where files in fields of a 1PW item never get updated

.github/workflows/ansible-count-hosts.yaml, .github/workflows/trigger-awx.yaml
Use virtual environment for python to allow the installation of libraries.
Change is necessary because the GitHub Runners are now based on Ubuntu 24.
Tested: https://github.com/hpi-schul-cloud/infra-schulcloud/actions/runs/11348888984
Before: https://github.com/hpi-schul-cloud/infra-schulcloud/actions/runs/11348562648
[OPS-7069](https://ticketsystem.dbildungscloud.de/browse/OPS-7069)
=> OPS-7069-fix-awx-workflow

cron-tools/Dockerfile
=> DBP-1083-adding-bsdextrautils-pkg-to-crontools

infra-tools/Dockerfile
https://ticketsystem.dbildungscloud.de/browse/BC-8619
=> BC-8619 add jq to infra-tools

docops/Dockerfile
=> DBP-0000 trigger build

.github/workflows/docopstoghcr-on-push.yaml
The current image leads to the following error when executing the Template in AWX:
```
{
"changed": true,
"stdout": "dtcw 0.51 - ##DTCW_GIT_HASH##\ndocToolchain 3.3.1\nOS/arch: Linux/x86_64\nAvailable docToolchain environments: local\nEnvironments with docToolchain [3.3.1]: none\nUsing environment: local\nIt seems docToolchain 3.3.1 is not installed. dtcw supports the\nfollowing docToolchain environments:\n\n1. 'local': to install docToolchain in [/home/docops/.doctoolchain] use\n\n    $ ./dtcw local install doctoolchain\n\n2. 'sdk': to install docToolchain with SDKMAN! (https://sdkman.io)\n\n    # First install SDKMAN!\n    $ curl -s \"https://get.sdkman.io\" | bash\n    # Then open a new shell and install docToolchain with\n    $ sdk install doctoolchain 3.3.1\n\nNote that running …
```
=> build docops image for docops-* tags

.github/workflows/imagetoghcr-on-push.yaml
Without this, no image tags was created when a docops-* git tag was created, which meant that building the docops image failed.
https://ticketsystem.dbildungscloud.de/browse/DOPS-163
This change will cause image tags of the form `docops-[0-9]+\.[0-9]+\.[0-9]+` to be created for any git tag that matches the pattern `docops-[0-9]+\.[0-9]+\.[0-9]+`. This follows the naming convention for image tags in the readme.
Since the git tag has to start with `docops-`, other images should not be affected as long as a git tag triggering the build and push action does not start with `docops-`.
=> DOPS-163 Create image tag for docops-* git tags

docops/Dockerfile
https://ticketsystem.dbildungscloud.de/browse/DOPS-190
=> DOPS-190 add sudo to be able to run doctoolchain in dops devcontainer
